### ISSUE TITLE
On ne voit pas les articles à vendre par la Foire dans l'historique de l'utilisateur

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#107]
Il faut voir tous les articles y compris les ceux vendu dans le cadre de la Foire. Cependant, ceux pour la Foire sont en lecture seule.

**Comment by willkoua** [comment]
![capture](https://cloud.githubusercontent.com/assets/5290381/21299665/b1b8c476-c56b-11e6-8e38-3f6366e8194b.PNG)

c<est bon la?

**Comment by krazdax5** [comment]
Oui. Peut-être mettre «Article de la Foire» au lieu de «Article de foire»?
