### ISSUE TITLE
Corriger le le champs du code à barre

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#11]
<img width="1456" alt="untitled" src="https://cloud.githubusercontent.com/assets/1693171/16253256/00dbcf9a-3803-11e6-9da8-7b16ee1ce8fe.png">

**Comment by willkoua** [comment]
je ne comprends pas. C'est quoi le bug? ou alors c'est quoi qu'il y a à corriger?

**Comment by krazdax5** [comment]
Le champs du code à barres est trop grand. Il faut le ramener au 1/3 de ça et le center avec l'image de la carte étudiante. Si tu corrige ça, dans le pull request, ajoute une capture d'écran du résultat de ta correction stp.

**Comment by willkoua** [comment]
est ce que je peux modifier le design de la page?? juste mieux aligner les champs du formulaire (de manière classique soit les uns en dessous des autres) . Je trouve ça mieux que ce qu'il y a actuellement

**Comment by krazdax5** [comment]
Lâche toi lousse! Juste mettre ici des captures d'écran stp.

**Comment by willkoua** [comment]
nouveau design
![2016-07-23_193628](https://cloud.githubusercontent.com/assets/5290381/17080857/2c51efe6-510e-11e6-8b42-c4966e4341a9.png)
8.png…]()

**Comment by krazdax5** [comment]
Drag drop où il est marqué «selecting them» en bas de là où tu écris le texte.

**Comment by krazdax5** [comment]
Est-ce que ça affiche bien dans un format mobile?

**Comment by willkoua** [comment]
oui mais il y a des manquements (marquer sur l'image)  pas liés à mon code.
![2016-07-23_193628](https://cloud.githubusercontent.com/assets/5290381/17080900/bb69ffe2-510f-11e6-8057-f234280e32c8.png)

**Comment by krazdax5** [comment]
Ok, regarde les deux premiers @media dans `site.css`. C'est là que c'est défini.

**Comment by krazdax5** [comment]
Réglé dans #33
