### ISSUE TITLE
Impossible d'accéder à la page de vente pour la Foire

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#111]
Peut-être un problème avec la condition d'affichage de la page. Il m'affiche toujours "Désolé. pas e n période de vente" alors que je suis en période de vente.

**Comment by krazdax5** [comment]
Idem pour la récupération...

**Comment by willkoua** [comment]
pour la page de vente ca fonctionne chez moi. Est ce que tu es sur d'etre en période de vente quant tu l'as testé?
