### ISSUE TITLE
Ajout d'un cours via une offre a un problème

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#13]
Quand on ajoute un cours via le formulaire d'une nouvelle offre, l'événement «change» ne se déclanche pas pour l'élément qui a été ajouté dynamiquement.

**Comment by willkoua** [comment]
je travail sur celui-ci

**Comment by willkoua** [comment]
pour être sur que je comprenne bien le problème: après l'enregistrement d'un nouveau cours, le input en hidden doit recevoir le sigle de ce cours ?

**Comment by krazdax5** [comment]
Oui. Le problème c'est justement que l'élément ajouté dynamiquement ne déclenche pas l'événement «onchange». Donc, le «hidden» ne se fait pas remplir.

``` javascript
$("#courses-list").on("change", "li>input[name='Course']", function () {
    $("#hidden-acronym").val($("input[name='Course']:checked").val());
});
```

Ce code là fonctionne seulement quand les éléments sont présents au chargement du DOM. Pourtant, le deuxième argument devrait regarder dans la liste à chaque fois, mais il ne le fait pas.
