### ISSUE TITLE
Offer.Price est inexistant dans le formulaire

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#15]
Le champs du prix a été oublié dans le formulaire de vente. SVP, ajoutez-le.

**Comment by krazdax5** [comment]
Requis pour #39

**Comment by willkoua** [comment]
je crois avoir résolu cette issue dans la dernière PR

**Comment by krazdax5** [comment]
Il reste encore des FIXME dans HomeController. dont un qui est justement ce problème.
![capture](https://cloud.githubusercontent.com/assets/1693171/18535633/e4ecda64-7ac3-11e6-97a0-469c2a79b5e2.PNG)

Le prix n'est jamais mis dans l'offre. (2e FIXME)

**Comment by willkoua** [comment]
est ce qu'on doit aussi définir un prix à l'article?
![2016-09-19_104618](https://cloud.githubusercontent.com/assets/5290381/18636324/5a1e645c-7e56-11e6-8f1b-20c3d810f698.png)

**Comment by krazdax5** [comment]
Non, juste à l'offre

On September 19, 2016 at 10:46:58 AM, willkoua (notifications@github.com) wrote:

est ce qu'on doit aussi définir un prix à l'article?
