### ISSUE TITLE
Offer.Title est inexistant dans le formulaire

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#16]
Il y a un titre pour l'article, mais pas de titre pour l'offre. Il faut faire attention à le mettre au bon endroit pour ne pas le confondre avec l'autre titre. Le formulaire de vente remplis une double fonction. Il ajoute un nouvel article au système et une nouvelle offre qui fait référence à un article.

**Comment by krazdax5** [comment]
Requis pour #39

**Comment by willkoua** [comment]
je ne comprend pas bien cette issue

**Comment by krazdax5** [comment]
Une **Offre** contient un titre et un **Article** aussi. Par contre, celui intégré dans la vue n'est que le titre de l'article. La différence entre les deux est qu'un titre d'article est, par exemple, «Introdution à la programmation - LOG101» et un titre d'offre, par exemple, «super offre, 10% de rabais!».

Ce que je crois, c'est qu'au moment de la conception je me suis planté. La meilleure approche selon moi serait de retirer complètement le titre de l'offre et garder seulement le titre de l'article.

**Comment by willkoua** [comment]
je crois avoir resolu cette issue dans la dernière PR

**Comment by krazdax5** [comment]
Les titres ne sont toujours pas bons dans la branches develop et dans HomeController. Il faut enlever complètement Title de l'offre et subtitle de l'article.

![capture](https://cloud.githubusercontent.com/assets/1693171/18535664/344b9596-7ac4-11e6-9632-a8e189579724.PNG)
