### ISSUE TITLE
Le profile ne fonctionne pas en certification

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#22]
Comme on peut le voir dans le capture d'écran ci-dessous, la page d'erreur générale est affichée lorsqu'on veut accéder au profil de l'utilisateur en cours.

![capture](https://cloud.githubusercontent.com/assets/1693171/16547810/7b32f834-4147-11e6-86c5-702d0b1d083f.PNG)

**Comment by krazdax5** [comment]
À priori, ce bout de code ne fonctionne pas. Le nom du input est «Type» selon le html dans la page.

```javascript
    $("input[name='Article']").on('change', function () {
        var value = $(this).val();

        if (value === 'C') {
            $("#calculator-models-dropdown").show('fast');
            $("#isbn-text-input").hide('fast');
        } else {
            $("#calculator-models-dropdown").hide('fast');
            $("#isbn-text-input").show('fast');
        }
    });
```

Donc Changer ` $("input[name='Article']")` pour ` $("input[name='Type']")`.

**Comment by krazdax5** [comment]
Requis pour #39

**Comment by willkoua** [comment]
ou est la classe ProfileViewModel ??

**Comment by krazdax5** [comment]
Check dans les ViewModels ou fait une recherche globale. C'est bizarre si
elle n'existe pas.
