### ISSUE TITLE
Le input du ISBN ne change pas pour un dropdown des types de calculatrices

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#23]
Dans la vue de vente, quand on change le type d'article à vendre pour une calculatrice, le champs de texte ne change pas pour un choix de modèle de calculatrice.

**Comment by krazdax5** [comment]
À priori, ce bout de code ne fonctionne pas. Le nom du input est «Type» selon le html dans la page.

``` javascript
    $("input[name='Article']").on('change', function () {
        var value = $(this).val();

        if (value === 'C') {
            $("#calculator-models-dropdown").show('fast');
            $("#isbn-text-input").hide('fast');
        } else {
            $("#calculator-models-dropdown").hide('fast');
            $("#isbn-text-input").show('fast');
        }
    });
```

Donc changer `$("input[name='Article']")` pour `$("input[name='Type']")`.

**Comment by willkoua** [comment]
tu peux m'assigner ici?? stp

**Comment by krazdax5** [comment]
En tant que contributeur externe, je ne peux pas t'assigner. Il faut que tu sois membre de l'équipe. Mais c'est bon, on se dit que le 👍 veut dire que j'ai consentis.

Ne pas oublier que j'ai seulement mis une piste de solution. C'est peut-être pas la solution.

**Comment by krazdax5** [comment]
Réglé dans #33

**Comment by willkoua** [comment]
oui jai oublié de merge :p
