### ISSUE TITLE
Convertir les <table> de données vers le plugin DataTables

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#28]
En d'autres mots, intégrer https://datatables.net.

**Comment by krazdax5** [comment]
Requis par #9  et #10

**Comment by willkoua** [comment]
ici tu parles uniquement des listes des données coté admin?

**Comment by krazdax5** [comment]
Toutes les <table> qui présentent des données «brutes» pour présentation et actions. Ces tableaux ont besoin d'être manipulés pour voir les données comme ont le souhaite (ex: sorting, paging, search, etc). Le plugin DataTables est parfait pour ça. Il faut l'intégrer dans l'affichage et faire la plomberie derrière pour que ça fonctionne. 

Donc, pour répondre à ta question, oui ceux dans le panneau d'administration sont à faire. Pour l'instant, je ne crois pas qu'il y en ait d'autre. Si tu penses qu'il pourrait y en avoir d'autre, juste poser la question.

**Comment by willkoua** [comment]
ok je prends cet issue

**Comment by willkoua** [comment]
est ce que  tu utilise la colonne Id dans ManageUser? car, je vois que tu mets aussi le Id dans un attribut au checkbox.

**Comment by krazdax5** [comment]
Oui. C'est pour identifier l'utilisateur. Quand on change son rôle ou qu'on le supprime. Regarde dans le javascript et cherche `.attr('id')`. Tu devrais trouver l'utilisation. Est-ce que tu as un problème relié à ça?

**Comment by willkoua** [comment]
` (User.Identity.GetUserId() != user.Id)`
stp est ce que tu peux m'expliquer cette condition ?

**Comment by krazdax5** [comment]
``` cs
if (User.Identity.GetUserId() != user.Id)
{
    ...
}
```

Cette condition est là pour que l'utilisateur en cours ne fasse pas des opérations sur son propre utilisateur dans l'administration des utilisateurs. C'est requis par le système.

**Comment by willkoua** [comment]
est ce que tu as des données test k je peux directement envoyer a la BD?

**Comment by krazdax5** [comment]
Nope. Ce que tu peux faire, c'est d'ajouter des utilisateurs à la main. Pas besoin de les authentifier avec Google. C'est seulement pour tester l'affichage.

``` sql
INSERT INTO AspNetUsers (
    FirstName, 
    LastName, 
    SubscribedAt, 
    BarCode, 
    PhoneNumberConfirmed, 
    TwoFactorEnabled, 
    LockoutEnabled, 
    UserName
) VALUES (
    'Charles', 
    'Levesque', 
    DATE(1,1,1970), 
    'FF000000', 
    0, 
    0, 
    0, 
    'charles.levesque.1@etsmtl.net'
)
```

**Comment by willkoua** [comment]
salut, s<il te plait d'ou vient la donnée `LivrETSID` ??

**Comment by krazdax5** [comment]
Ça fait partie du domaine. C'est requis par le système. Dans la branche `feature/sell_fair_article` du dépôt d'origine, il y a une classe qui s'occupe d'implémenter ce standard (`TRIBSTD01Helper.cs`). Si tu en as de besoin, `git checkout origin feature/sell_fair_article -- LivrETS/Models/TRIBSTD01Helper.cs`. Voici le document du standard:

[TRIBSTD01-2016NomenclatureducodedesarticlesvenduslorsdelaFoireauxLivres.pdf](https://github.com/Tributerre/LivrETS-Web/files/408144/TRIBSTD01-2016NomenclatureducodedesarticlesvenduslorsdelaFoireauxLivres.pdf)

**Comment by willkoua** [comment]
s'il te plait est que tu peux me dire comment récupérer cette donnée?

**Comment by krazdax5** [comment]
Soit plus spécifique stp. Qu'est-ce que tu cherches à faire?

**Comment by willkoua** [comment]
> var listUser = (from user in db.Users
>                             orderby user.FirstName descending
>                                 select new {
>                                     FirstName = user.FirstName,
>                                     LastName = user.LastName,
>                                     SubscribedAt = user.SubscribedAt,
>                                     BarCode = user.BarCode,
>                                     Email = user.Email,
>                                     UserName = user.UserName,
>                                     Id = user.Id,
>                                     //LivrETSID = user.LivrETSID,
>                                     role=user.Roles.Join(db.Roles, userRole=>userRole.RoleId, role=>role.Id, (userRole, role)=>role).Select(role=>role.Name) 
>                                 }).ToList();

si je decomment le commentaire, je reçois une erreur comme quoi la donnée nest pas accessible `

**Comment by willkoua** [comment]
en faite pour etre plus précis, on ne peut pas avoir accès à cette données en passant par les linq :(

**Comment by krazdax5** [comment]
Les LivrETSID sont sur les modèles `Fair`, `Article` et `ApplicationUser`. Si tu regardes à l'intérieur de ces classes, tu pourrais remarquer le décorateur `[NotMapped]` au-dessus de cette propriété. Ça veut dire que ce n'est pas dans la base de données. Donc ce n'est pas récupérable en faisant une requête LINQ à la BD. Dans la version que t'as, ces propriétés sont calculées à chaque fois que tu les accèdes.

Voici un exemple:

``` cs
var user = Repository.GetUserBy(Id: "blalaslkdnd-askj-dfnsk");
user.LivrETSID;  // Ceci est le LivrETSID
user.Id;  // Ceci est l'Id de la base de données
```

En gros, ce que tu fais n'est juste pas valide de base dans la version des modèles que tu as. L'autre chose que je ne comprend toujours pas, c'est pourquoi tu fais cette requête et pourquoi tu as besoin du LivrETSID.

**Comment by willkoua** [comment]
ok.. j'ai trouvé un autre moyen d'y avoir acces merci :)
