### ISSUE TITLE
Erreur d'affichage dans la page de cueillette

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#55]
Tout le texte est beaucoup trop à gauche. Peut-être révisé la page au complet pour l'intégrer au gabarit.

![capture](https://cloud.githubusercontent.com/assets/1693171/19099951/d4ec8040-8a88-11e6-8fd9-aa5df5b7cec2.PNG)

**Comment by willkoua** [comment]
Je l'ai résolu ce problème. ok je vais regarder

**Comment by willkoua** [comment]
je viens de regarder. Ça fonctionne chez moi. Peut être que tu n'es pas sur la bonne branche celle où le problème est résolu.

**Comment by krazdax5** [comment]
Je suis sur la branche du pull request.

**Comment by willkoua** [comment]
actuellement je suis sur ma branche `general-home-search` est ce ton cas?

**Comment by krazdax5** [comment]
Tromper de conversation. Je ne suis pas sur cette branche. Lie la PR qui corrige cet issue stp. En mentionnant le numéro de cet issue (#55) en commentaire dans la PR.

**Comment by willkoua** [comment]
j'ai réglé le problème dans un commit d'intégration dans une des branches sur les quelle j'ai travaillé. Je n'avais pas vue l'issue #55

**Comment by krazdax5** [comment]
Si le commit en question est dans une PR, mentionne l'issue ici présent (#55) dedans en commentaire stp. Si ce n'est pas encore en PR, quand t'auras créé la PR qui corrige ce problème, mentionne cet issue ici (#55) dedans en commentaire stp.
