### ISSUE TITLE
Modifier l'écran de connexion pour l'adapter au nouveau prototype

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#6]
![connexion](https://cloud.githubusercontent.com/assets/1693171/14369137/859ef4a8-fcf0-11e5-99c8-b6dcd66c57af.png)

**Comment by krazdax5** [comment]
Il manque le logo du site au centre.

**Comment by willkoua** [comment]
est ce que le logo est déjà disponible ??

**Comment by krazdax5** [comment]
Non. L'étiquette «on hold» va être enlevé quand il sera prêt.
