### ISSUE TITLE
Pied de page incorrect

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#89]
![screen shot 2016-12-03 at 1 57 24 pm](https://cloud.githubusercontent.com/assets/1693171/20861531/748595c8-b960-11e6-9e74-9e8f972a97cb.png)

* Enlever la section Shipping & Delivery
* Enlever la section Newsletter
* Mettre des infos crédibles dans la section Suivez-Nous: Adresse de l'ÉTS + numéro de tél de l'ÉTS
* Enlever les Lorem Ipsum de trop dans la section Suivez-nous

**Comment by willkoua** [comment]
est ce qu<ils sont sur un autre reseaux social que facebook?

**Comment by willkoua** [comment]
Est ce que je peux utiliser le "\ propos" de luer page FB?
![capture](https://cloud.githubusercontent.com/assets/5290381/20861705/96259daa-b964-11e6-89d7-6328aa1bf5e8.PNG)

**Comment by krazdax5** [comment]
Y'a un Lorem Ipsum encore dans contactez-nous. Faut l'enlever.

Est-ce que c'est possible d'ajouté une section à droite nommée «Nos Partenaires». Comme contenu, met le logo de l'ÉTS pour l'instant.

**Comment by willkoua** [comment]
ok

**Comment by willkoua** [comment]
c'est correct?
![capture](https://cloud.githubusercontent.com/assets/5290381/20861847/241f1502-b968-11e6-8566-7f71f3c20db6.PNG)

**Comment by krazdax5** [comment]
C'est bon
