### ISSUE TITLE
Ajouter la pagination pour l'administration des utilisateurs

### ISSUE THREAD

**Issue by krazdax5** [Tributerre/LivrETS-Web#9]
- Pagination avec le nombre maximal de résultat par page (15, 20, 25)

**Comment by willkoua** [comment]
comment est ce qu'on accède au coté admin?

**Comment by krazdax5** [comment]
Juste une petite précision, ce ticket devrait être réglé avec l'ajout de DataTables (voir #28 ). Donc ne pas faire une pagination depuis rien.

Pour accéder au panneau admin, tu dois être admin! =D
Comme tu dois être le seul utilisateur sur ton poste de développement, ajoutes-toi à bras dans la BD en tant qu'admin. En d'autres mots, ajoutes une entré dans la table **AspNetUserRole**. Il y a déjà un rôle Administrator (copie son ID).

Il faut ensuite que tu te déconnectes du site web et tu te reconnectes et le tour est joué.

**Comment by willkoua** [comment]
oui ca je sais .. je parle de l'url c'est /admin ?

**Comment by krazdax5** [comment]
Routage 101 dans ASP MVC:

Par défaut, les urls c'est AdresseIP:Port/{Nom du contrôleur sans «Controller»}/{Nom de la méthode}. Par exemple, Il y a le contrôleur **HomeController** avec la méthode `Index()`. L'URL est `/Home/Index`.

**Comment by willkoua** [comment]
ha oui!! ok merci :)
